config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurants, only: [ :index, :show, :new, :create] do
    resources :reviews, only: [ :new, :create ]
  end

    namespace :admin do
      resources :restaurants, except: [ :index, :show, :new, :create]
    end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :name, presence: true, uniqueness: true
  validates :address, presence: true, uniqueness: true
  validates :phone_number, presence: true, uniqueness: true
  validates :category, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"], allow_nil: false }
  # GIVEN CATEGORY WILL BE A FIXED LIST, AND THEREFORE A DROP
  # DOWN, AM I CORRECT IN ASSUMING WE DON'T NEED TO VALIDATE IT AGAINST ANYTHING OTHER THAN PRESENCE?
  # IF INCLUSION IS THE RIGHT VALIDATION, WHAT HAPPENS IF THE LIST/ OPTIONS IS HUNDREDS OF OPTIONS LONG?
  # IS THERE A BETTER PLACE TO STORE THEM?

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true
  validates :rating, inclusion: { in: [0, 1, 2, 3, 4, 5], allow_nil: false }, numericality: {:only_integer => true}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.create(restaurant_params)
    redirect_to restaurants_path
  end


end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/create.html.erb
create.html.erb

app/views/restaurants/index.html.erb
<h1>Restaurants#index</h1>

<h3><%= link_to "Add new restaurant", new_restaurant_path %></h3>
<% @restaurants.each do |restaurant| %>
  <h2><%= restaurant.name %></h2>
  <h3><%= restaurant.category %></h3>
  <h3><%= restaurant.phone_number %></h3>
  <%= link_to "Show Restaurant", restaurant_path(restaurant) %>
<% end %>

app/views/restaurants/new.html.erb
<h1>Restaurants#new</h1>

<%= simple_form(@restaurant) do |restaurant| %>
  <%= restaurant.label :name %>
  <%= restaurant.text_field :name %>

  <%= restaurant.label :address %>
  <%= restaurant.text_field :address %>

  <%= restaurant.label :phone_number %>
  <%= restaurant.text_field :phone_number %>

  <%= restaurant.label :category %>
  <%= restaurant.radio_buttons :category %>

  <%= restaurant.submit %>
<% end %>

app/views/restaurants/show.html.erb
<h1>Restaurant#show</h1>

  <h1><%= @restaurant.name %></h1>
  <h3><%= restaurant.category %></h3>
  <h3><%= restaurant.phone_number %></h3>
  <h3><%= restaurant.address %></h3>